### PR TITLE
DB初期化をdbunit.ymlで指定するようにした

### LINKED ISSUE #74: testがflaky
一度に全テスト実行すると落ちるテストがある
一方で一つ一つ実行すると全て通る

原因はテスト間のデータベース初期化が失敗しているため
DBRiderの使い方に問題がありそう
要調査

### PR DESCRIPTION
**Pull request by h-takesg**
`@DataSet(cleanBefore = true)`が効いていない？
このため`BillServiceTest`が連続実行では3,4個目のテストが失敗していた．
各Test毎に`cleanAfter = true`を指定したら連続実行でも通った．
`After`なのは各テストが自分で後始末をするという捉え方．
Fix #74 

ついでに使用しない`@AutoConfigureMockMvc`を削除．

### CODE REVIEW

**Review by Haur514 — CHANGES_REQUESTED** [review]
# 問題点
自分の環境では`MembersControllerTest`の`normalGetAllMembers()`が落ちる．
Purchaseの外部キー制約が引っかかっちゃって，悪さをしてるらしい．

> java.lang.RuntimeException: Could not create dataset for test 'normalGetAllMembers'.
 at com.github.database.rider.core.RiderRunner.runBeforeTest([RiderRunner.java:46](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.github.database.rider.junit5.DBUnitExtension.beforeTestExecution([DBUnitExtension.java:69](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
Caused by: com.github.database.rider.core.exception.DataBaseSeedingException: Could not initialize dataset: MembersController/normalGetAllMembers/before.yaml
 at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet([DataSetExecutorImpl.java:142](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.github.database.rider.core.RiderRunner.runBeforeTest([RiderRunner.java:44](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 ... 55 more
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "member" violates foreign key constraint "fkq9jpnu7wc1b02gnol85hw9su2" on table "purchase"
  Detail: Key (id)=(h-takesg) is still referenced from table "purchase".
 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse([QueryExecutorImpl.java:2675](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.core.v3.QueryExecutorImpl.processResults([QueryExecutorImpl.java:2365](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.core.v3.QueryExecutorImpl.execute([QueryExecutorImpl.java:355](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.executeInternal([PgStatement.java:490](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.execute([PgStatement.java:408](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.executeWithFlags([PgStatement.java:329](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.executeCachedSql([PgStatement.java:315](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.executeWithFlags([PgStatement.java:291](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.execute([PgStatement.java:286](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.zaxxer.hikari.pool.ProxyStatement.execute([ProxyStatement.java:94](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
 at org.dbunit.database.statement.SimpleStatement.executeBatch([SimpleStatement.java:69](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.dbunit.operation.DeleteAllOperation.execute([DeleteAllOperation.java:126](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.dbunit.operation.CompositeOperation.execute([CompositeOperation.java:79](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet([DataSetExecutorImpl.java:133](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 ... 56 more

# 解決策
`BillsControllerTest`とか`PurchaseControllerTest`でも`@DataSet`に`cleanAfter=true`足して良いと思う．テストメソッドは独立しているので．
自分の環境では`PurchaseControllerTest`の`@DataSet`に`cleanAfter=true`を追加したらテストが全て通った．

**Comment by h-takesg** [comment]
手元で再現できなかったので推測
vscodeでの実行に原因がありそう
Rebuild関連が期待通りに動いてくれないことがある

## 検証
fix-testブランチをチェックアウトののち，
1. gradle直で叩いてみてほしい
    ```
    $ ./gradlew test --tests="*"
    ```
2. cache削除して実行してみてほしい
    1. `backend/bin/`を削除
    2. F1 > Java: Rebuild Project

ともに成功するならvscode（のJava Extension）の問題

**Comment by Haur514** [comment]
# 検証
1. gradle直で叩く -> 全てのテストで成功
2. cache削除し，VSCodeで実行 -> 今度は`ItemsControllerTest`が失敗

2で，全ての`@DataSet`に`cleanAfter=true`を追加したら全てのテストに通過することを確認
エラーメッセージを見る限り，ItemsControllerTestがPurchasesControlllerTestの影響を受けてそう

> java.lang.RuntimeException: Could not create dataset for test 'normalGetAllItems'.
 at com.github.database.rider.core.RiderRunner.runBeforeTest([RiderRunner.java:46](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.github.database.rider.junit5.DBUnitExtension.beforeTestExecution([DBUnitExtension.java:69](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
Caused by: com.github.database.rider.core.exception.DataBaseSeedingException: Could not initialize dataset: ItemsController/normalGetAllItems/before.yaml
 at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet([DataSetExecutorImpl.java:142](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.github.database.rider.core.RiderRunner.runBeforeTest([RiderRunner.java:44](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 ... 55 more
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "item" violates foreign key constraint "fkemduimgakuywg7g70dd54sshw" on table "purchase"
  Detail: Key (id)=(cola) is still referenced from table "purchase".
 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse([QueryExecutorImpl.java:2675](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.core.v3.QueryExecutorImpl.processResults([QueryExecutorImpl.java:2365](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.core.v3.QueryExecutorImpl.execute([QueryExecutorImpl.java:355](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.executeInternal([PgStatement.java:490](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.execute([PgStatement.java:408](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.executeWithFlags([PgStatement.java:329](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.executeCachedSql([PgStatement.java:315](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.executeWithFlags([PgStatement.java:291](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.postgresql.jdbc.PgStatement.execute([PgStatement.java:286](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.zaxxer.hikari.pool.ProxyStatement.execute([ProxyStatement.java:94](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
 at org.dbunit.database.statement.SimpleStatement.executeBatch([SimpleStatement.java:69](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.dbunit.operation.DeleteAllOperation.execute([DeleteAllOperation.java:126](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.dbunit.operation.CompositeOperation.execute([CompositeOperation.java:79](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet([DataSetExecutorImpl.java:133](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 ... 56 more

# 可能性
1. 自分の環境/手順がおかしい
3. VSCodeの拡張機能に問題がある
4. テストがフレイキー
1か3かなという気がしている

**Comment by h-takesg** [comment]
初期化の指定をテスト毎に書くのではなく，テスト全体に一括で指定した．
`./gradlew test`とvscode guiからの実行で全通過を確認済み

**Comment by grtw2116** [comment]
> @grtw2116 君の環境ではどう？？

image

IntelliJ IDEAから実行しましたが，テストは問題なく実行されています

**Review by Haur514 — APPROVED** [review]
LGTM

**Pull request merged**
